charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/templates/job.yaml, charts/openfga/templates/rbac.yaml
Adds a database migration job to the OpenFGA Helm chart if `postgres.enabled=true` or `mysql.enabled=true`. This job will run `openfga migrate`, and each pod will run an init container waiting on the migration job to complete before returning. This ensures that only one migration job is run instead of 1 per init container.
To test these changes locally, before they are released, you can use:
```
$ cd helm-charts
$ helm install openfga ./charts/openfga \
--set datastore.engine=postgres \
--set datastore.uri="postgres://postgres:password@openfga-postgresql.default.svc.cluster.local:5432/postgres?sslmode=disable" \
--set postgres.enabled=true \
--set postgresql.auth.postgresPassword=password \
--set postgresql.auth.database=postgres
```
Here's a video capture of the process working as …
=> fix: add database migration job to openfga chart

charts/openfga/Chart.yaml
Bump OpenFGA Chart `version` and `appVersion`.
=> chore: bump OpenFGA `appVersion` and Chart version

charts/openfga/Chart.yaml, charts/openfga/README.md, charts/openfga/templates/deployment.yaml, charts/openfga/templates/service.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This PR enhances the Helm chart for OpenFGA by providing descriptions and improvements to the fields in the `values.schema.json` file, which Helm uses to enforce validation constraints on the values provided during installation and Artifact Hub uses this file to self-document the values of the Helm chart.
See
=> docs: improve OpenFGA Chart documentation with`values.schema.json`

charts/benchmark/Chart.yaml, charts/benchmark/templates/pod.yaml, charts/benchmark/values.yaml
This wires up the various test params that can be provided to the benchmark script in the openfga/benchmarks repository.
=> chore: add benchmark params to OpenFGA Benchmark chart

charts/benchmark/templates/pod.yaml
typo in helm chart - should be Values not values
=> fix: typo in value

charts/benchmark/Chart.yaml
=> chore: bump version

charts/openfga/Chart.yaml
Bump up to the latest OpenFGA server release version (`v0.4.3`) and bump the chart version to force a new release.
=> chore: bump OpenFGA appVersion and chart version

charts/benchmark/Chart.lock, charts/benchmark/Chart.yaml
Bump the dependency on the OpenFGA chart in the benchmark chart.
=> chore: bump the OpenFGA dependency in the benchmark chart

LICENSE, README.md
=> chore: add Apache-2.0 license

charts/benchmark/Chart.yaml, charts/benchmark/templates/pod.yaml, charts/benchmark/values.yaml
This PR makes the memory used by the k6 container configurable.
=> feat: make memory configurable

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/templates/job.yaml
Addresses #47 by adding security contexts to appropriate containers.
https://github.com/openfga/helm-charts/issues/47
- [x ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x ] The correct base branch is being used, if not `main`
- [x ] I have added tests to validate that the change in functionality is working as expected
=> fix: all containers will abide by helm configured security context

charts/openfga/Chart.yaml, charts/openfga/templates/job.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Add support for attaching extra annotations on the migrations job's manifest.
Example scenario:
In kubernetes environment with automatic istio sidecar injection, I would like to disable it on migration job pod.
=> feat: add support for migration job annotations

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Allow clients to specify extra resources to tune the deployment manifest:
- extra environment variables
- extra volumes
- extra volume mounts
=> feat: add extra config to deployment

charts/openfga/Chart.yaml, charts/openfga/templates/job.yaml
When annotations are specified to a `Job`, they should also propagate to the `Pod` itself.
This PR ensures that annotations also exist within the `template.metadata` so that they're carried across. 
Example `values.yaml`
```yaml
migrate:
annotations:
sidecar.istio.io/inject: 'false'
```
Helm should output
```yaml
apiVersion: batch/v1
kind: Job
metadata:
name: openfga-migrate
namespace: default
annotations:
sidecar.istio.io/inject: 'false'
spec:
template:
metadata:
annotations:
sidecar.istio.io/inject: 'false'
spec:
containers:
- name: migrate-database
<snip>
```
Resulting in this Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
name: openfga-migrate-75gw7
namespace: default
annotations:
sidecar.istio.io/inject: 'false'
spec:
<snip>
```
=> fix: Job annotations should be passed to the pod

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
bump after recent openfga release
https://github.com/openfga/openfga/releases/tag/v1.3.3
=> bump appVersion to v1.3.3

charts/openfga/Chart.yaml
Bump after recent openfga release
https://github.com/openfga/openfga/releases/tag/v1.3.4
=> bump appVersion to v1.3.4

charts/openfga/templates/job.yaml
Pass tolerations, affinity, and nodeSelector configuration along to the job definition.
Current configuration does not allow specifying tolerations on the job config, resulting in the deployment pods, but never the job pod being scheduled on infra that requires taint tolerations. This PR adds three existing node configuration items to the job definition as well, so both are controlled in the same manner.
Personally, I only need tolerations but the others seemed like they could/should be shared so I carried over all three.
N/A
- None of the values being added to the job definition appear to exist in the values schema, so I wasn't sure whether to add them or not, let me know and I can add any docs needed!
=> fix(job): add node configuration settings to job pod as well

charts/openfga/templates/ingress.yaml, charts/openfga/values.yaml
Allow different ports for different paths
=> feat: allow different ports for paths in ingress

.github/workflows/release.yml
closes #78 
https://github.com/helm/chart-releaser#common-error-messages
=> ci: skip uploading if release exists

charts/openfga/Chart.yaml
Bump `appVersion` up to the latest OpenFGA release `v1.3.6`
=> chore: bump appVersion up to latest OpenFGA release

.github/workflows/CODEOWNERS
=> chore: delete unused CODEOWNERS file

charts/openfga/templates/job.yaml
=> fix: sidecars in the migrate job

charts/openfga/Chart.yaml
Bump the chart and appVersion for OpenFGA.
=> chore(openfga): bump OpenFGA Helm chart appVersion

.github/CODEOWNERS
=> chore: change owner team to be

charts/openfga/Chart.yaml
Bump up the OpenFGA chart `appVersion` to the most recent release of OpenFGA.
https://github.com/openfga/openfga/releases/tag/v1.5.0
=> chore(deps): bump OpenFGA chart appVersion

charts/openfga/Chart.yaml
The current homepage link resolves to a 404 - this PR fixes that and points it to the right place.
=> chore(docs): update Chart.yaml to fix the homepage link

charts/openfga/templates/job.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Add migrate timeout option to values
- https://github.com/openfga/openfga/blob/v1.5.3/cmd/migrate/flags.go#L28-L29
=> feat: add migrate timeout option to values

charts/openfga/Chart.yaml
Bump openfga to 15.7
https://github.com/openfga/openfga/releases/tag/v1.5.7
=> chore: update openfga to 1.5.7

charts/openfga/Chart.yaml
=> release(openfga): bump chart version to v0.2.9

charts/openfga/Chart.yaml
Bump for `v1.8.0`
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> chore: update chart for v1.8.0

charts/openfga/templates/deployment.yaml
FIX: adds missing commonLabels to Pod resources
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> fix: pod commonLabels

charts/openfga/Chart.yaml
bump openfga version for [release of v1.8.1](https://github.com/openfga/openfga/releases/tag/v1.8.1)
=> chore: bump openfga version

charts/openfga/Chart.yaml
Bump for [release v1.8.2](https://github.com/openfga/openfga/releases/tag/v1.8.2)
=> chore: bump openfga version to 1.8.2

charts/openfga/Chart.yaml
https://github.com/openfga/openfga/releases/tag/v1.8.3
=> bump openfga version to 1.8.3

charts/openfga/Chart.yaml
Bump helm chart to match OpenFGA [version v1.8.4](https://github.com/openfga/openfga/releases/tag/v1.8.4)
=> chore: bump openfga to 1.8.4

.github/CODEOWNERS
=> chore: Update CODEOWNERS to include maintainers

charts/openfga/Chart.yaml
Partner PR for https://github.com/openfga/openfga/pull/2283
=> chore: update OpenFGA version to 1.8.5

charts/openfga/Chart.yaml
=> chore: update openfga to v1.8.6

charts/openfga/Chart.yaml
Update helm chart for [v1.8.7](https://github.com/openfga/openfga/releases/tag/v1.8.7)
=> chore: update OpenFGA to v1.8.7

.github/dependabot.yaml
=> chore(ci): fix dependabot

charts/openfga/Chart.yaml
Changes in this release: https://github.com/openfga/helm-charts/compare/openfga-0.2.26...release/v0.2.27
- https://github.com/openfga/helm-charts/pull/207
- https://github.com/openfga/helm-charts/pull/209
- https://github.com/openfga/helm-charts/pull/210
=> release: v0.2.27

charts/openfga/Chart.yaml
Bump OpenFGA helm chart version
https://github.com/openfga/openfga/releases/tag/v1.8.11
=> chore: update OpenFGA to v1.8.11

charts/openfga/Chart.yaml
update openfga to [v1.8.12](https://github.com/openfga/openfga/releases/tag/v1.8.12)
=> update openfga to v1.8.12

charts/openfga/Chart.yaml
=> release: v0.2.31
