charts/openfga/Chart.yaml, charts/openfga/README.md
Fix a broken link in the OpenFGA chart README, and bump the chart version to force Artifact Hub to update the README for the package.
=> fix: broken link in OpenFGA chart README

charts/openfga/Chart.yaml, charts/openfga/templates/rbac.yaml
This prefixes the `job-status-reader` role and rolebinding resource with the Helm release name so that separate helm releases don't collide.
To test this out you can do the following:
```
helm install goofyparrot openfga/openfga
helm install goofyparrot2 openfga/openfga # this will fail because of the collision
```
then run it with these changes instead
```
git clone <this-repo>
git checkout fix-jobstatusreader-resource
cd <this-repo>
helm install goofyparrot ./charts/openfga
helm install goofyparrot2 ./charts/openfga # this will succeed
```
=> fix: prefix job-status-reader role and binding with helm release

.github/workflows/release.yml
Adds the `openfga` chart repository to the release workflow. It was missing and so the most recent release workflow failed.
See https://github.com/openfga/helm-charts/actions/runs/4659155991/jobs/8245702192
=> ci: add missing `openfga` chart repository to release workflow

.github/workflows/CODEOWNERS
chore of adding openfga as owner
=> chore: add openfga as codeowner

charts/benchmark/Chart.yaml, charts/benchmark/templates/pod.yaml
testListObject needs to be treated as string prior to being set as environment variable
=> fix: testListObject env variable as string

.gitignore, charts/benchmark/Chart.yaml, charts/benchmark/templates/pod.yaml, charts/benchmark/values.yaml
Add configurable k6 setup timeout.
Close https://github.com/openfga/helm-charts/issues/14
=> feat: configurable k6 setup timeout

charts/benchmark/Chart.yaml, charts/benchmark/templates/pod.yaml, charts/benchmark/values.yaml
Tweak default k6 timeout value.  Also note that time is in ms, not in seconds - thus we should rename variable to fit the actual description.
N/A
=> chore: update default timeout value

charts/benchmark/Chart.yaml, charts/openfga/Chart.yaml
Update helm chart to use openfga release [v1.0.1](https://github.com/openfga/openfga/releases/tag/v1.0.1)
=> chore: bump openfga version to 1.0.1

charts/benchmark/Chart.yaml, charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml
Thanks to @alee792 for spotting the issue: https://github.com/openfga/helm-charts/pull/21#issuecomment-1513712717
- https://github.com/openfga/openfga/pull/697
=> fix: update path of grpc_health_probe as it was changed in OpenFGA v1.0.1

charts/benchmark/Chart.yaml, charts/benchmark/templates/pod.yaml, charts/benchmark/values.yaml
Allow configuration on benchmark for number of tuples per write and which user we want to run check/list objects on
=> feat(benchmark): add configuration for num tuples per write

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Allow specifying a secret for the datastore URI.
In some environments, it might be unfeasible to include the datastore URI in plaintext within the Helm values specified. An example would be using an external Database and wanting to keep the secrets of that database outside the Git repo where the project is deployed.
To address this, I'm adding an option where an external secret can be referenced, and instead of specifying the URI directly in the deployment file, the deployment will instead refer to that secret.
This allows the URI to be populated independently of the chart itself and provisioned securely.
Example:
```yaml
datastore:
uriSecret: openfga-datastore
```
Resulting deployment snippet:
```yaml
...
- name: OPENFGA_DATASTORE_URI
valueFrom:
secretKeyRef:
name: openfga-datastore
key: …
```
=> feat: specify a secret for the datastore URI

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/templates/job.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This addresses issue #28, by decoupling the migration execution from the embedded database.
Instead of deciding if the migration is run on whether `postgres.enabled` or `mysql.enabled`, that would involve the creation of the database within Kubernetes, decide the migration based on the engine defined in the datastore, by checking the value of `datastore.engine`.
That way, whenever the data store engine is one that requires running migrations, they are automatically created and run accordingly.
#28
=> fix(openfga): allow migration without embedded db

charts/benchmark/templates/pod.yaml
This change is to prevent `OOMKilled` errors in AWS EKS. In the future we can make this configurable.
Not tested
=> fix: increase memory assigned to k6 container

charts/benchmark/Chart.yaml
To fix this: https://github.com/openfga/helm-charts/actions/runs/5202120710/jobs/9383267760
```
Error: error creating GitHub release benchmark-0.0.10: POST https://api.github.com/repos/openfga/helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
=> chore: release new benchmark chart version

charts/openfga/Chart.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This changes the default value of the `datastore.applyMigrations` so that quick installs apply migrations by default. If you are redeploying OpenFGA or if you are rolling OpenFGA out with a pre-migrated datastore, then you can set this value to false.
Fixes #42
=> fix: default `datastore.applyMigrations` to true for quick installs

charts/openfga/templates/deployment.yaml, charts/openfga/templates/service.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Specify `.annotations` and `.service.annotations` in the chart, that allow adding additional annotations to the deployment and to the service resources, respectively.
#35
=> fix(openfga): allow service and deployment annotations

charts/openfga/Chart.yaml
Bumps the OpenFGA chart `appVersion` up to the latest release of OpenFGA.
https://github.com/openfga/openfga/releases/tag/v1.1.1
=> chore: bump OpenFGA chart `appVersion`

charts/openfga/Chart.yaml, charts/openfga/templates/job.yaml
This PR updates the Job template to account for any passed `serviceAccountNames`, which may be necessary for certain configurations of Kubernetes.
It also bumps the application version from `v1.1.1.` to `v1.2.0`
=> fix: add serviceAccountNames to jobs and bump the app version

charts/openfga/Chart.lock, charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Add default liveness and startup probes and allow custom probes to be specified for OpenFGA containers.
https://github.com/orgs/openfga/discussions/172
=> chore: add more support for liveness and startup probes

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml
If `playground.enabled=false` then we shouldn't omit the env variable since the Playground is enabled by default in the OpenFGA server. This makes sure that we set the env variable to true/false regardless of its value.
Closes https://github.com/openfga/helm-charts/issues/54
=> fix: Playground should disable if `playground.enabled=false`

charts/openfga/Chart.lock, charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/templates/job.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Adding ability to specify sidecars in the deployment, default is none.
Used example:
https://github.com/bitnami/charts/tree/main/bitnami/keycloak 
For defining sidecars, because I noticed this chart already leverages a couple other bitnami packages.
- [ X ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [  ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ X  ] The correct base branch is being used, if not `main`
=> feat: Add sidecars to deployment

charts/openfga/templates/deployment.yaml
```
helm install openfga ./charts/openfga --set experimentals='{list-objects,check-query-cache}'
```
closes #57
=> fix: allow setting `experimentals` config value

charts/openfga/Chart.yaml, charts/openfga/templates/hpa.yaml
In support of correcting issue #65 I've updated the HPA API version and corrected the spec structure.
Updated the apiVersion to autoscalingv2
Updated .spec.metrics.type[*].resource to use .target structure
Pull is based on correcting issue #65 
The reference for the API version being deprecated can be found at https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
The reference for the spec change can be found at https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-resource-metrics
=> Updating HorizontalPodAutoscalar

.github/cr.yaml
Set `--generate-release-notes` to have `cr upload` use Github's automatic release notes.
Closes https://github.com/openfga/helm-charts/issues/56
=> chore: generate release notes

.github/dependabot.yaml, .github/workflows/test.yml
- Add dependabot config for github actions
- Bump version for helm/chart-test
```
Run helm/chart-testing-action@v2.4.0
with:
version: v3.8.0
yamllint_version: [1](https://github.com/openfga/helm-charts/pull/72/checks#step:5:1).[2](https://github.com/openfga/helm-charts/pull/72/checks#step:5:2)7.1
yamale_version: [3](https://github.com/openfga/helm-charts/pull/72/checks#step:5:3).0.[4](https://github.com/openfga/helm-charts/pull/72/checks#step:5:4)
env:
pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
LD_LIBRARY_PATH: …
```
=> ci: fix failing lint-test job

charts/openfga/templates/deployment.yaml, charts/openfga/templates/job.yaml, charts/openfga/values.yaml
Allow resources limits and requests to be configured for the migration job.
Added the following to values.yaml
```diff
datastore:
engine: memory
uri:
uriSecret:
maxCacheSize:
maxOpenConns:
maxIdleConns:
connMaxIdleTime:
connMaxLifetime:
applyMigrations: true
+  migrations:
+    resources: {}
```
=> feat: add resources for migration containers

README.md
=> chore(docs): add license badge to README

charts/openfga/templates/deployment.yaml, charts/openfga/values.yaml
Allow custom images to be used for the wait-for-migration initContainer. This is because we sometimes want to use private repos/images.
=> feat: allow use of custom image for wait-for-migration initContainer

charts/openfga/Chart.lock, charts/openfga/Chart.yaml
The current version (12.2.3) defined in Chart.yaml includes a bug in the Helm chart that's fixed with 12.5.8 and later:
* https://github.com/bitnami/charts/pull/17140
* https://github.com/bitnami/charts/commit/ffa4eeb0e853fd63fced31d1bd443c6587354f87
This PR upgrade the PostgreSQL helm chart to the latest 12.x version. I've chosen this version rather than the newest (13.2.21) because it keeps the PostgreSQL major version the same (15.x vs 16.x). I'm not familiar enough with OpenFGA to say if PostgreSQL 16 (released 14.09.2023) is already supported.
=> Update PostgreSQL chart to 12.12.10

charts/openfga/Chart.yaml, charts/openfga/templates/job.yaml, charts/openfga/templates/rbac.yaml, charts/openfga/values.yaml
Added annotations to the job in order for the migration job to be deleted after a successful run.
In reference to Issue #69 I've added hook annotations to the migration job in order for the job to be deleted and then recreated during a helm upgrade/rollback.
For views on how to add hooks to jobs, one can reference the Helm documentation at: https://helm.sh/docs/topics/charts_hooks/
=> feat: added hook to job to delete/recreate during upgrade/rollback

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Add `additionalProperties: false` to the top level `values.schema.json` specification so that we avoid introducing new values into the `values.yaml` file without having explicit documentation for it.
As part of ☝️ it was brought to my attention that we didn't have some of the common Helm chart values specified in the `values.schema.json`, so coverage has been added for those undocumented values.
Added entries for the top-level subchart properties to the `values.schema.json` file so we can do `additionalProperties: false` and still pass the Helm linter. See https://github.com/helm/helm/issues/10392 for more info.
=> chore(lint): add values.schema.json validation strict

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This makes the init container that waits for migrations optional via a
`waitForMigrations` flag. If disabled, it does not render the
`initContainer` alongside the role and role binding it uses.
In tools such as ArgoCD, the waves (which can be set throught he helm
annotations we already have) ensure that a resource is applied before
another one. So this waiting init container may not be needed. Let's
make it configurable for deployments that don't require this.
Note that the option defaults to `true` as to keep the current logic and
functionality as it is.
=> feat: Add flag to wait for migrations to complete (or not)

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Allows to pass setting `OPENFGA_LOG_TIMESTAMP_FORMAT` env var via `values.yaml` file. 
Exposes the new functionality added in https://github.com/openfga/openfga/pull/1330
=> feat: add log timestamp format

charts/openfga/Chart.lock, charts/openfga/Chart.yaml, charts/openfga/README.md, charts/openfga/values.schema.json, charts/openfga/values.yaml
In #89 I broke the Helm chart for those users who want to quickly deploy Postgres alongside the OpenFGA service. This fixes that. I verified the commands in the README work.
https://github.com/openfga/helm-charts/pull/89
=> fix: postgresql subchart

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml
If `datastore.engine` is set to `memory` (the current default) hard code replica count to `1`. Any other engine will continue using whatever `replicaCount` is set to, by default it's `3`.
https://github.com/openfga/openfga/issues/1431
=> fix: set replica to 1 when using memory datastore

charts/openfga/Chart.yaml, charts/openfga/templates/_helpers.tpl, charts/openfga/templates/servicemonitor.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This PR adds the possibility to use the ServiceMonitor custom resource from the [prometheus-operator](https://github.com/prometheus-community/prometheus-operator) to scrape the `/metrics` endpoint
The changes enable an user of the Chart to deploy a ServiceMonitor custom resource. This is needed if the user wants to use the prometheus-operator to scrape the metrics endpoint
=> feat(openfga): add servicemonitor to OpenFGA chart

charts/openfga/values.schema.json
Allow `global` property in values schema to be able to use the chart as dependency chart.
This PR adds a `global` property to `openfga` Helm chart values schema file. This allows using the Helm chart as a dependency chart and provide values to it.
Fixes #106
=> feat: allow global in helm values to allow openfga as dependency chart

charts/openfga/Chart.yaml, charts/openfga/values.yaml
@lachnerd pointed out that we're using two different versions of `k8s-wait-for` image version, so this makes them the same.
https://github.com/openfga/helm-charts/issues/120
=> chore: pin to the same k8s-wait-for image version

charts/openfga/Chart.yaml, charts/openfga/templates/job.yaml
Adds image pull secrets to the migration job.
Image pull secrets are currently configurable for the OpenFGA deployment, but not the migrate job.
This makes it difficult to use the chart in scenarios where you want to pull images from a private registry (e.g. a Docker Hub mirror). 
Another option here is to add them to the service account, but I think this way is clearer and compatible if the service account is disabled.
I have tested this locally and it allows the chart to be installed with all images configured to pull from a private registry.
If the change warrants more discussion I'm happy to open up an issue - but it looks like something that might have just been missed out.
=> fix: add image pull secrets to migration job

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Upgrades to OpenFGA v1.5.4 which includes experimental support for the ListUsers API. Along with the version bump is support for this new API's configurations as well as adding in some missing configurations.
~**Note:** This PR is in draft until 1.5.4 is released; there is [1.5.4-rc1](https://github.com/openfga/openfga/releases/tag/v1.5.4-rc1) out though.~
- [ListUsers OpenFGA PR](https://github.com/openfga/openfga/pull/1433)
- [1.5.4-rc1 release](https://github.com/openfga/openfga/releases/tag/v1.5.4-rc1)
=> chore: upgrading to v1.5.4 for `ListUsers` API support

charts/openfga/templates/deployment.yaml, charts/openfga/values.yaml
feat(openfga): allow extraInitContainers for the openfga deployment
This PR adds the ability for an end user to define additional `initContainers` that should run on the openfga deployment.
=> feat(openfga): allow `extraInitContainers` for the openfga deployment

charts/openfga/Chart.yaml, charts/openfga/templates/job.yaml
From reading the code I see no way of providing the same `extraEnvVars` as done to the deployment for the migration job. The only way I can see is to directly add `datastore.uri` as part of the values file which is not something we want since it is a secret and something we want to commit to a git repository. It is from what I've found (please correct me if so) not possible to to use something like ExternalSecret to load the value dynamically rather than hardcoding it in the values file.
I'd like to be able to do something like
We are currently running this version of the chart in production and it works just fine.
```
openfga:
extraEnvVars:
- name: OPENFGA_DATASTORE_URI
valueFrom:
secretKeyRef:
name: openfga-external-secrets
key: OPENFGA_DATASTORE_URI
```
but it is currently not picked …
=> feat: include "extraEnvVars" as part of the migration job

charts/openfga/Chart.yaml, charts/openfga/templates/deployment.yaml
migrate job has backoff limit 1. Which means, it might fail once before succeeding (typically due to db not ready for connection). This pr allows such a scenario to be considered successful.
- https://github.com/groundnuty/k8s-wait-for/blob/master/wait_for.sh#L36-L43
=> fix: wait for at least a successful migrate job run

charts/openfga/templates/deployment.yaml
There's a typo in the deployment file that prevents the initContainer to be deployed.
The bug was introduced in #104
=> fix: typo in datastore.waitForMigrations

charts/openfga/Chart.yaml
Updating OpenFGA to the recently-released [v1.5.6](https://github.com/openfga/openfga/releases/tag/v1.5.6).
- [OpenFGA v1.5.6](https://github.com/openfga/openfga/releases/tag/v1.5.6)
=> chore: Updating OpenFGA to 1.5.6

charts/openfga/templates/job.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This PR adds the extraVolumes and extraVolumeMounts to the migration job.
As this PR (https://github.com/openfga/helm-charts/pull/142) also already did, I added extraVolumes and extraVolumeMounts to the migrate job allowing for different scenarios not possible without, eg. mounting CA bundles or mounting secrets via SPC for the database credentials to be used by the job.
Compared to the other PR I also added the default values in the values.yaml and added the new values to the validation schema.
https://github.com/openfga/helm-charts/pull/142
=> feat: add extraMounts and volumes to migrate job

charts/openfga/templates/extra-manifests.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Adding arbitrary manifests to the helm chart 
I'd like to be able to deploy other resources not included in the chart; Gateway HTTPRoutes, CloudnativePG Clusters etc.
- [Based on the prior art from ArgoCD](https://github.com/argoproj/argo-helm/blob/8b02b6d9b828902ba0d9ae1e6ddb4f060a5975ca/charts/argo-cd/values.yaml#L564-L591) - https://github.com/argoproj/argo-helm/blob/8b02b6d9b828902ba0d9ae1e6ddb4f060a5975ca/charts/argo-cd/templates/extra-manifests.yaml
=> feat: add extraObjects 

charts/openfga/templates/deployment.yaml
Added quotes to ensure the environment variable value is always treated as a string. Zitadel and Azure seemingly offer audiences that are longInts.
https://github.com/openfga/helm-charts/issues/152
=> fix: add quotes around oidc options

charts/openfga/README.md, charts/openfga/templates/_helpers.tpl, charts/openfga/values.schema.json, charts/openfga/values.yaml
Common Labels to Helm Chart
Adds optional common labels support which gets added to all deployable Kube resources.
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> feat: add Common Labels Support

charts/openfga/Chart.yaml
This release contains the following changes:
- feat: add Common Labels Support (#167, #168) - thanks @bagnaram
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> release: v0.2.17

charts/openfga/templates/deployment.yaml
Pass the value of .Values.grpc.tls.enabled into OPENFGA_GRPC_TLS_ENABLED as a string (i.e. "true", "false") instead of the boolean value
=> fix: stringify OPENFGA_GRPC_TLS_ENABLED

charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This PR provides the ability to add labels to openfga pods.
Some mechanisms such as Network Policies or Webhooks uses the concept of [LabelSelector](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/). This PR adds a `podExtraLabels` value next to the `podAnnotations` so that extra labels can be added to the openfga pods.
This change was validated through snapshot testing in an internal fork.
There is no testing framework in place here. Providing the mentioned snapshot testing framework is out of this PR's scope so I won't check the last box.
=> feat(openfga): Allow extra labels specific to pods

charts/openfga/values.yaml
The values.schema.json sets the default value of datastore.migrationType to job, but this attribute is missing in the values.yaml file.
N/A
=> fix: add the missing default value for datastore.migrationType

charts/openfga/values.schema.json
I want to activate the access-control experimental feature, but the json schema don't allow it. 
https://openfga.dev/docs/getting-started/setup-openfga/access-control#i-enable-access-control-in-the-server
=> fix(schema): Add enable-access-control to experimental array

charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This PR provides the ability to add lifecycle hook to openfga pods.
Some mechanisms such as preStop or postStart hooks uses the concept of [Lifecycle](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks).
This PR adds a lifecycle value next to the resources so that lifecycle hook can be added to the openfga pods.
We use lifecycle to add preStop hook that waits few seconds before terminating pod to make sure iptable update completion.
Below screenshot is result of `helm template lifecycle-test .` with lifecycle value of
```
lifecycle:
preStop:
exec:
command:
- sh
- -c
- sleep 10
```
=> feat(openfga): Allow lifecycle hook specific to pods

charts/openfga/Chart.yaml
=> chore: bump openfga to v1.8.8

charts/openfga/templates/deployment.yaml
Gating the `OPENFGA_HTTP_ENABLED` and `OPENFGA_METRICS_ENABLED` blocks means that when the value is set to false, the env vars are not set. This causes the deployment to use the default values for these configs which is `Enabled: true`. Instead we should do the same thing as we do in the `OPENFGA_PLAYGROUND_ENABLED` env var and always set it so that these can be disabled by helm users.
N/A
=> bug: Allow disabling the http service and metrics with helm

charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
This PR introduces support for `TopologySpreadConstraints` for Kubernetes version >1.18.0 that we can customize to improve pods spread, leading to high availability.
=> feat: add topology constraints support

charts/openfga/templates/tests/test-connection.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Provides the ability to extends the definition of the connection test pod.
The helm chart uses a pod to test its correct deployment.
There is no ability to extend the definition of this pod and therefore to make the pod match any policy in place.
Such policy preventing the test pod deployment might be (not exhaustive):
* Resource quota without ability to provide a default value with a limit range
* ValidatingWebhookConfiguration based constraints with products such as kyverno or OPA
Here is a working example of a configuration matching the resource quota constraint :
```yaml
testContainerSpec:
resources:
limits:
cpu: 1
memory: 250M
requests:
cpu: 50m
memory: 250M
testPodSpec:
securityContext:
runAsNonRoot: true
runAsUser: 1000
runAsGroup: 1000
```
This feature is documented by the value …
=> feat(test): Allow extension of test pod to allow matching local policy

charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
The k8s native grpc probes don't support tls so we need to use the exec version if tls is enabled. While users can always specify custom probes, this updates the defaults so that things work out of the box for most usecases.
Fixes #3
=> bug: Update default probes to work with tls enabled

charts/openfga/Chart.yaml
=> chore: bump openfga to v1.8.9

charts/openfga/templates/deployment.yaml
It seems like there was a typo in one of the flags in #205. This fixes the issue.
See #205
=> bug: Fix typo for probe

charts/openfga/templates/deployment.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Add `requestTimeout` value.
Adds `requestTimeout` to the values which maps to OpenFGA's `requestTimeout`/ OPENFGA_REQUEST_TIMEOUT option:
https://openfga.dev/docs/getting-started/setup-openfga/configuration#list-of-options
This is actually necessary to fully support the `listObjectsDeadline` option because OpenFGA will return an error on startup if the value of `listObjectsDeadline` < `requestTimeout`.
```
panic: configured request timeout (6s) cannot be lower than 'listObjectsDeadline' config (30s)
```
=> feat: add requestTimeout configuration value

.github/dependabot.yaml
Dependabot has just added support for helm: https://github.blog/changelog/2025-04-09-dependabot-version-updates-now-support-helm/
=> chore(ci): enable dependabot updates to helm-charts

charts/openfga/templates/deployment.yaml, charts/openfga/templates/tests/test-auth-secret.yaml, charts/openfga/values.schema.json, charts/openfga/values.yaml
Previously, preshared keys were only configurable directly through values.yaml, this change adds the ability to fetch preshared keys from Kubernetes secrets instead.
The new keysSecret field in the authn.preshared configuration allows specifying a secret name that contains the keys.
This PR adds a new security enhancement to the Helm chart that allows fetching preshared authentication keys from Kubernetes secrets instead of storing them directly in values.yaml.
Key changes:
- Added `keysSecret` field to `authn.preshared` configuration in values.schema.json
- Updated deployment.yaml to support reading keys from the specified secret
- Keys in the secret should be comma-separated in the `keys` field
This change follows the same pattern as `datastore.uriSecret`. …
=> feat(authn): add support for fetching preshared keys from secrets

.github/workflows/test.yml
Potential fix for [https://github.com/openfga/helm-charts/security/code-scanning/1](https://github.com/openfga/helm-charts/security/code-scanning/1)
To fix the problem, add a `permissions` block to the workflow to explicitly set the minimum required permissions for the `GITHUB_TOKEN`. Since the workflow only checks out code and runs tests/linting, it only needs read access to repository contents. The best way to do this is to add `permissions: contents: read` at the top level of the workflow file, just below the `name` and before the `on` key. This will apply the least privilege principle to all jobs in the workflow without changing any existing functionality.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> chore(ci): restrict lint & test workflow permissions to only read contents
